name: Build and Deploy Frontend to Vercel

on:
  push:
    paths:
      - "learning_platform_fe/**"
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.19.0"

      - name: Install dependencies
        run: |
          cd learning_platform_fe
          npm ci

      - name: Build
        run: |
          cd learning_platform_fe
          npm run build

      - name: Vercel Deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: learning_platform_fe
          prod: true
